name: WSL-enabled powershell
description: 'Execute a script in powershell as session >= 2.'

inputs:
  exec:
    description: Script to execute
    required: true
  max-attempts:
    description: Maximum number of connection attempts 
    default: "20"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Execute the script
      shell: powershell
      env:
        exec: ${{ inputs.exec }}
      run: |
        # Cleaning up previous runs
        if( $(Test-Path -Path ".\script.ps1") ) {
          Remove-Item -Path ".\script.ps1" -Force | Out-Null
        }

        "${env:exec}" > script.ps1

        powershell.exe -File script.ps1